/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Util.GerenteDeJanelas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.HEIGHT;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author tiago
 */
public class Principal extends javax.swing.JFrame {

    GerenteDeJanelas gerenteDeJanelas;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //centralizado
        setLocationRelativeTo(null);
        //maximizado
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.gerenteDeJanelas = new GerenteDeJanelas(jDesktopPane1);

        //data
        data();
        hora();
    }

    public void data() {
        Date data = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtData.setText("Data: " + sdf.format(data));
    }

    public void hora() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date data = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss a");
                txtHora.setText("Hora: " + sdf.format(data));
            }

        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        txtData = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnResidencia = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnPessoas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVeiculos = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnVisitas = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUANTUM SYSTEM - CONTROLE DE ACESSO");
        setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 153));

        txtData.setBackground(new java.awt.Color(255, 255, 255));
        txtData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtData.setForeground(new java.awt.Color(0, 102, 255));

        txtHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(842, Short.MAX_VALUE)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(txtHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(596, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);

        jSeparator1.setBackground(new java.awt.Color(0, 153, 255));
        jToolBar1.add(jSeparator1);

        btnResidencia.setBackground(new java.awt.Color(255, 255, 255));
        btnResidencia.setText("RESIDENCIAS");
        btnResidencia.setFocusable(false);
        btnResidencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResidencia.setMaximumSize(new java.awt.Dimension(100, 60));
        btnResidencia.setMinimumSize(new java.awt.Dimension(100, 60));
        btnResidencia.setPreferredSize(new java.awt.Dimension(100, 60));
        btnResidencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResidenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnResidencia);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.add(jSeparator2);

        btnPessoas.setBackground(new java.awt.Color(255, 255, 255));
        btnPessoas.setText("PESSOAS");
        btnPessoas.setFocusable(false);
        btnPessoas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPessoas.setMaximumSize(new java.awt.Dimension(100, 60));
        btnPessoas.setMinimumSize(new java.awt.Dimension(100, 60));
        btnPessoas.setPreferredSize(new java.awt.Dimension(100, 60));
        btnPessoas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPessoas);
        jToolBar1.add(jSeparator3);

        btnVeiculos.setBackground(new java.awt.Color(255, 255, 255));
        btnVeiculos.setText("VEÍCULOS");
        btnVeiculos.setFocusable(false);
        btnVeiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVeiculos.setMaximumSize(new java.awt.Dimension(100, 60));
        btnVeiculos.setMinimumSize(new java.awt.Dimension(100, 60));
        btnVeiculos.setPreferredSize(new java.awt.Dimension(100, 60));
        btnVeiculos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVeiculos);
        jToolBar1.add(jSeparator4);

        btnVisitas.setBackground(new java.awt.Color(255, 255, 255));
        btnVisitas.setText("VISÍTAS");
        btnVisitas.setFocusable(false);
        btnVisitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVisitas.setMaximumSize(new java.awt.Dimension(100, 60));
        btnVisitas.setMinimumSize(new java.awt.Dimension(100, 60));
        btnVisitas.setPreferredSize(new java.awt.Dimension(100, 60));
        btnVisitas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVisitas);
        jToolBar1.add(jSeparator5);

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setMaximumSize(new java.awt.Dimension(100, 60));
        btnSair.setMinimumSize(new java.awt.Dimension(100, 60));
        btnSair.setPreferredSize(new java.awt.Dimension(100, 60));
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResidenciaActionPerformed
        gerenteDeJanelas.abrirJanelas(UIResidencias.getInstancia());
    }//GEN-LAST:event_btnResidenciaActionPerformed

    private void btnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoasActionPerformed
        gerenteDeJanelas.abrirJanelas(UIPessoas.getInstancia());
    }//GEN-LAST:event_btnPessoasActionPerformed

    private void btnVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculosActionPerformed
        gerenteDeJanelas.abrirJanelas(UIVeiculos.getInstancia());
    }//GEN-LAST:event_btnVeiculosActionPerformed

    private void btnVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitasActionPerformed
        gerenteDeJanelas.abrirJanelas(UIVisitas.getInstancia());
    }//GEN-LAST:event_btnVisitasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        ImageIcon question = new ImageIcon("src/img/question.png");
        int x = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Sair?", "ATENÇÃO", JOptionPane.OK_CANCEL_OPTION, HEIGHT, question);
        if (x == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPessoas;
    private javax.swing.JButton btnResidencia;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVeiculos;
    private javax.swing.JButton btnVisitas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtHora;
    // End of variables declaration//GEN-END:variables
}
