/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ConnectionFactory;
import Util.GerenteDeJanelas;
import com.alee.extended.label.WebLinkLabel;
import com.alee.laf.WebLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.HEIGHT;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.sql.Connection;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tiago
 */
public class Principal extends javax.swing.JFrame {

    GerenteDeJanelas gerenteDeJanelas;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        setLocationRelativeTo(null); //centralizado
        setExtendedState(JFrame.MAXIMIZED_BOTH);//maximizado
        this.gerenteDeJanelas = new GerenteDeJanelas(jDesktopPane1);

        //data
        data();
        hora();
        setIcon();
        WebLookAndFeel.install();
    }

    public void data() {
        Date data = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txtData.setText(sdf.format(data));
    }

    public void hora() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date hora = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm a");
                txtHora.setText(sdf.format(hora));
            }
        }
        ).start();
    }

    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/img/fundo.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        txtData = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnResidencia = new javax.swing.JButton();
        btnPessoas = new javax.swing.JButton();
        btnVeiculos = new javax.swing.JButton();
        btnVisitas = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnContato = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUANTUM SYSTEM - CONTROLE DE ACESSO");
        setBackground(new java.awt.Color(255, 255, 255));

        txtData.setBackground(new java.awt.Color(255, 255, 255));
        txtData.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N

        txtHora.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N

        WebLinkLabel email = new WebLinkLabel ();
        email.setEmailLink ( "tiagoseg@live.com" );
        email.setText("tiagoseg@live.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(599, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);

        btnResidencia.setBackground(new java.awt.Color(255, 255, 255));
        btnResidencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnResidencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/residencias.png"))); // NOI18N
        btnResidencia.setText("RESIDÊNCIAS");
        btnResidencia.setToolTipText("");
        btnResidencia.setFocusable(false);
        btnResidencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResidencia.setMaximumSize(new java.awt.Dimension(100, 60));
        btnResidencia.setMinimumSize(new java.awt.Dimension(100, 60));
        btnResidencia.setPreferredSize(new java.awt.Dimension(100, 60));
        btnResidencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResidenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnResidencia);

        btnPessoas.setBackground(new java.awt.Color(255, 255, 255));
        btnPessoas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pessoas.png"))); // NOI18N
        btnPessoas.setText("PESSOAS");
        btnPessoas.setFocusable(false);
        btnPessoas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPessoas.setMaximumSize(new java.awt.Dimension(100, 60));
        btnPessoas.setMinimumSize(new java.awt.Dimension(100, 60));
        btnPessoas.setPreferredSize(new java.awt.Dimension(100, 60));
        btnPessoas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPessoas);

        btnVeiculos.setBackground(new java.awt.Color(255, 255, 255));
        btnVeiculos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/car.png"))); // NOI18N
        btnVeiculos.setText("VEÍCULOS");
        btnVeiculos.setFocusable(false);
        btnVeiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVeiculos.setMaximumSize(new java.awt.Dimension(100, 60));
        btnVeiculos.setMinimumSize(new java.awt.Dimension(100, 60));
        btnVeiculos.setPreferredSize(new java.awt.Dimension(100, 60));
        btnVeiculos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVeiculos);

        btnVisitas.setBackground(new java.awt.Color(255, 255, 255));
        btnVisitas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visitas.png"))); // NOI18N
        btnVisitas.setText("VISÍTAS");
        btnVisitas.setFocusable(false);
        btnVisitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVisitas.setMaximumSize(new java.awt.Dimension(100, 60));
        btnVisitas.setMinimumSize(new java.awt.Dimension(100, 60));
        btnVisitas.setPreferredSize(new java.awt.Dimension(100, 60));
        btnVisitas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVisitas);

        btnRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorio.png"))); // NOI18N
        btnRelatorio.setText("RELATÓRIO");
        btnRelatorio.setFocusable(false);
        btnRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorio.setMaximumSize(new java.awt.Dimension(100, 60));
        btnRelatorio.setMinimumSize(new java.awt.Dimension(100, 60));
        btnRelatorio.setPreferredSize(new java.awt.Dimension(100, 60));
        btnRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRelatorio);

        btnContato.setBackground(new java.awt.Color(255, 255, 255));
        btnContato.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contato.png"))); // NOI18N
        btnContato.setText("CONTATO");
        btnContato.setFocusable(false);
        btnContato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnContato);

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setMaximumSize(new java.awt.Dimension(100, 60));
        btnSair.setMinimumSize(new java.awt.Dimension(100, 60));
        btnSair.setPreferredSize(new java.awt.Dimension(100, 60));
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResidenciaActionPerformed
        gerenteDeJanelas.abrirJanelas(UIResidencias.getInstancia());
    }//GEN-LAST:event_btnResidenciaActionPerformed

    private void btnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoasActionPerformed
        gerenteDeJanelas.abrirJanelas(UIPessoas.getInstancia());
    }//GEN-LAST:event_btnPessoasActionPerformed

    private void btnVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculosActionPerformed
        gerenteDeJanelas.abrirJanelas(UIVeiculos.getInstancia());
    }//GEN-LAST:event_btnVeiculosActionPerformed

    private void btnVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitasActionPerformed
        gerenteDeJanelas.abrirJanelas(UIVisitas.getInstancia());
    }//GEN-LAST:event_btnVisitasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int x = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Sair?", "ATENÇÃO", JOptionPane.OK_CANCEL_OPTION, HEIGHT);
        if (x == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        Connection conn = ConnectionFactory.getConnection();
        String src = "src/Relatorio/relatorio_visitas.jasper";
        JasperPrint jasperPrint = null;
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("Error: " + ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatoActionPerformed
        gerenteDeJanelas.abrirJanelas(UIContato.getInstancia());
    }//GEN-LAST:event_btnContatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows XP".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContato;
    private javax.swing.JButton btnPessoas;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnResidencia;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVeiculos;
    private javax.swing.JButton btnVisitas;
    private javax.swing.JLabel email;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtHora;
    // End of variables declaration//GEN-END:variables
}
